version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:23.6.1
    steps:
      - checkout
      - run: echo "this is the build job"
  
  workflows:
    build_and_test:
      jobs:
        - build